(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
getBody[x0_,\[Theta]_]:=Module[{params},
params={width->.4, height->.2,R->2};
Graphics[{Red,Rotate[Translate[Rectangle[{-width/2,0},{width/2,height}],{x0,R}],-\[Theta],{x0,0}]}]/.params
]
getBall[x0_]:=Module[{params, \[Psi]},
params={R->2};
\[Psi]=x0/R;
Graphics@{Gray,DiskSegment[{x0,0},R,{-\[Psi],Pi-\[Psi]}],Black,DiskSegment[{x0,0},R,{Pi-\[Psi],2Pi-\[Psi]}]}/.params
]
getBB8[x0_,\[Theta]_]:=Show[getBall[x0],getBody[x0,\[Theta]]]



